# Generated by Django 5.0.4 on 2024-05-22 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_goal_state_alter_grantgoal_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='subgrantgoal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subgrantgoal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.CharField(choices=[('HEIGHT', 'HG'), ('MIDDLE', 'MD'), ('LOW', 'LW')], max_length=8),
        ),
        migrations.AlterField(
            model_name='goal',
            name='state',
            field=models.CharField(choices=[('NOT STARTED', 'NS'), ('DOING', 'DG'), ('DONE', 'DN')], max_length=16),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='priority',
            field=models.CharField(choices=[('HEIGHT', 'HG'), ('MIDDLE', 'MD'), ('LOW', 'LW')], max_length=8),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='state',
            field=models.CharField(choices=[('NOT STARTED', 'NS'), ('DOING', 'DG'), ('DONE', 'DN')], max_length=16),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('HEIGHT', 'HG'), ('MIDDLE', 'MD'), ('LOW', 'LW')], max_length=8),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('NOT STARTED', 'NS'), ('DOING', 'DG'), ('DONE', 'DN')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='priority',
            field=models.CharField(choices=[('HEIGHT', 'HG'), ('MIDDLE', 'MD'), ('LOW', 'LW')], max_length=8),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='state',
            field=models.CharField(choices=[('NOT STARTED', 'NS'), ('DOING', 'DG'), ('DONE', 'DN')], max_length=16),
        ),
    ]
