# Generated by Django 5.0.4 on 2024-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_goal_priority_alter_goal_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='state',
            field=models.CharField(choices=[('DONE', 'DN'), ('PENDING', 'PD'), ('IN PROGRESS', 'IP')], max_length=16),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='state',
            field=models.CharField(choices=[('DONE', 'DN'), ('PENDING', 'PD'), ('IN PROGRESS', 'IP')], max_length=16),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('DONE', 'DN'), ('PENDING', 'PD'), ('IN PROGRESS', 'IP')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='state',
            field=models.CharField(choices=[('DONE', 'DN'), ('PENDING', 'PD'), ('IN PROGRESS', 'IP')], max_length=16),
        ),
    ]
